// Read-only chain access — ethers provider + contract instances.
//
// There is no signer here, and there must never be one. The backend holds no
// Ethereum key: staking, registration, and rentals are all signed by the user's
// own wallet in the browser. Everything in this file is `view` calls and log
// queries. (The Irys storage wallet in config/irys.js is a separate, deliberate
// exception — it can only pay for Arweave bytes, never touch Alexandria.)
//
// Addresses and ABIs come from ./abis/*.json, generated by scripts/sync-abis.js
// from the AlexandriaSmartContract Ignition deployment. Env vars may override
// each address; a mismatch is logged loudly rather than silently preferred,
// because pointing the event listener at a stale contract produces an index
// that looks healthy and is entirely wrong.

const path = require('path');
const { ethers } = require('ethers');

const libraryArtifact = require('../abis/library.json');
const stakeArtifact = require('../abis/stake.json');
const rentArtifact = require('../abis/rent.json');
const tokenArtifact = require('../abis/token.json');
const paymentArtifact = require('../abis/payment.json');

// ─── Network ─────────────────────────────────────────────────────────────────

const CHAIN_ID = libraryArtifact.chainId;

// The public Base Sepolia endpoint returns "no backend is currently healthy"
// often enough that a single-URL provider makes the status endpoints flap. Any
// comma-separated list here becomes a FallbackProvider that tries them in order.
const DEFAULT_RPC_URLS = [
  'https://base-sepolia-rpc.publicnode.com',
  'https://sepolia.base.org',
];

function rpcUrls() {
  const configured = (process.env.BASE_TESTNET_RPC_URL || '')
    .split(',')
    .map((u) => u.trim())
    .filter(Boolean);
  return configured.length ? configured : DEFAULT_RPC_URLS;
}

// How often the event listener polls for new logs. Base blocks every ~2s, but
// the listener is not latency-critical — it only moves a Postgres status column
// that the frontend re-reads on refresh — so this trades freshness for RPC quota.
const POLL_INTERVAL_MS = Number(process.env.CHAIN_POLL_INTERVAL_MS || 12_000);

// Oldest block any watched contract existed at — the floor for a cold backfill.
// Base Sepolia is ~45M blocks deep; scanning from genesis is not an option, and
// nothing addressed to these contracts can exist before they were deployed.
// CHAIN_START_BLOCK overrides it (useful to skip ancient history on a fresh index).
const DEPLOYMENT_BLOCK = Math.min(
  ...[libraryArtifact, stakeArtifact, rentArtifact]
    .map((a) => a.deploymentBlock)
    .filter((b) => typeof b === 'number')
);

const START_BLOCK = Number(process.env.CHAIN_START_BLOCK || DEPLOYMENT_BLOCK);

let _provider;

/**
 * The shared read-only provider, built once.
 *
 * `staticNetwork` stops ethers re-querying eth_chainId before every call, which
 * on a flaky public RPC is a second chance to fail per request.
 *
 * @returns {import('ethers').Provider}
 */
function getProvider() {
  if (_provider) return _provider;

  const urls = rpcUrls();
  const network = new ethers.Network(`base-sepolia-${CHAIN_ID}`, CHAIN_ID);

  if (urls.length === 1) {
    _provider = new ethers.JsonRpcProvider(urls[0], network, { staticNetwork: network });
  } else {
    // quorum 1: take the first healthy answer instead of demanding agreement.
    // These are all reads of the same public chain state — the risk being
    // managed is an endpoint being down, not an endpoint lying.
    _provider = new ethers.FallbackProvider(
      urls.map((url, index) => ({
        provider: new ethers.JsonRpcProvider(url, network, { staticNetwork: network }),
        priority: index + 1,
        stallTimeout: 3000,
        weight: 1,
      })),
      network,
      { quorum: 1 }
    );
  }

  _provider.pollingInterval = POLL_INTERVAL_MS;
  return _provider;
}

// ─── Addresses ───────────────────────────────────────────────────────────────

// Env var name → artifact, so an operator can repoint a single contract without
// regenerating the ABI files (useful when one contract is redeployed alone).
const CONTRACT_SPECS = {
  library: { artifact: libraryArtifact, envVar: 'LIBRARY_CONTRACT_ADDRESS' },
  stake: { artifact: stakeArtifact, envVar: 'STAKE_CONTRACT_ADDRESS' },
  rent: { artifact: rentArtifact, envVar: 'RENT_CONTRACT_ADDRESS' },
  token: { artifact: tokenArtifact, envVar: 'TOKEN_CONTRACT_ADDRESS' },
  payment: { artifact: paymentArtifact, envVar: 'PAYMENT_CONTRACT_ADDRESS' },
};

/**
 * Resolve one contract's address: env override if present and valid, otherwise
 * the address recorded in the committed deployment artifact.
 */
function resolveAddress(name) {
  const { artifact, envVar } = CONTRACT_SPECS[name];
  const override = (process.env[envVar] || '').trim();

  if (!override) return artifact.address;

  if (!ethers.isAddress(override)) {
    console.warn(`[chain] ${envVar}="${override}" is not a valid address — using ${artifact.address} from abis/${name}.json`);
    return artifact.address;
  }

  if (override.toLowerCase() !== artifact.address.toLowerCase()) {
    console.warn(
      `[chain] ${envVar} (${override}) disagrees with abis/${name}.json (${artifact.address}). ` +
        'Using the env value. If the contract was redeployed, re-run scripts/sync-abis.js.'
    );
  }

  return ethers.getAddress(override);
}

let _contracts;

/**
 * Read-only contract instances, keyed by short name.
 * @returns {{ library: import('ethers').Contract, stake: import('ethers').Contract, rent: import('ethers').Contract, token: import('ethers').Contract, payment: import('ethers').Contract }}
 */
function getContracts() {
  if (_contracts) return _contracts;

  const provider = getProvider();
  _contracts = {};

  for (const [name, { artifact }] of Object.entries(CONTRACT_SPECS)) {
    _contracts[name] = new ethers.Contract(resolveAddress(name), artifact.abi, provider);
  }

  return _contracts;
}

/**
 * Addresses actually in use, for logging and the health endpoint.
 * @returns {Record<string, string>}
 */
function contractAddresses() {
  const out = {};
  for (const name of Object.keys(CONTRACT_SPECS)) out[name] = resolveAddress(name);
  return out;
}

// ─── Registrar signer (the one write path) ───────────────────────────────────
//
// ⚠️ This is a deliberate, narrow exception to "the backend holds no Ethereum
// key". The deployed AlexandriaLibrary.registerUpload() is `onlyAuthorized` and
// takes an explicit `uploader` address — it was written for a backend that
// registers on an archivist's behalf, and deployment.md step 3b says so. An
// archivist calling it from their own wallet reverts with "Not authorized".
//
// What this key can and cannot do:
//   CAN    call library.registerUpload() — record a hash + uploader + metadata
//   CANNOT stake, rent, transfer $ALEX, resolve challenges, or blacklist anyone
//          (those are onlyOwner or require the caller to be the staker/renter)
//
// So the blast radius of a compromised registrar key is spam registrations, not
// stolen funds. Keep it that way: never grant this address ownership of any
// contract, and never reuse it as the treasury.
//
// Registration is OFF unless BACKEND_PRIVATE_KEY is set. With it unset the
// backend is exactly as read-only as it was before this existed.

const BACKEND_PRIVATE_KEY = (process.env.BACKEND_PRIVATE_KEY || '').trim();
const BACKEND_WALLET_ADDRESS = (process.env.BACKEND_WALLET_ADDRESS || '').trim();

let _signer;
let _signerError = null;

/**
 * Refuse to hand out a signer when this process is a test run.
 *
 * Learned the hard way: `uploadFlow.test.js` stubs Postgres, Irys, Lit, and
 * validation, but not the chain. The moment a real BACKEND_PRIVATE_KEY existed,
 * running that suite sent six live transactions and wrote junk hashes into
 * AlexandriaLibrary — permanently, because registerUpload has no delete.
 *
 * The entrypoint check is deliberate: a guard that depends on every future test
 * author remembering to set NODE_ENV or add a stub is a guard that eventually
 * fails. This one cannot be forgotten, because it reads the process itself.
 * NODE_ENV is honoured too, for runners that invoke tests some other way.
 *
 * @returns {string|null} why writes are blocked, or null if they are allowed
 */
function chainWritesBlocked() {
  if (process.env.NODE_ENV === 'test') return 'NODE_ENV=test';
  if (process.env.CHAIN_WRITES_ENABLED === 'false') return 'CHAIN_WRITES_ENABLED=false';

  const entry = require.main && require.main.filename;
  if (entry && (/\.test\.js$/.test(entry) || /[\\/]tests[\\/]/.test(entry))) {
    return `test entrypoint (${path.basename(entry)})`;
  }

  return null;
}

/**
 * The registrar wallet, or null when no key is configured.
 *
 * When BACKEND_WALLET_ADDRESS is also set, the derived address must match it.
 * That check exists because the failure it prevents is miserable to debug: a
 * wrong key produces a perfectly valid wallet that simply is not authorized, so
 * every registration reverts with "Not authorized" and looks like a missing
 * setAuthorizedCaller rather than a mistyped secret.
 *
 * @returns {import('ethers').Wallet|null}
 */
function getSigner() {
  if (_signer !== undefined) return _signer;

  const blocked = chainWritesBlocked();
  if (blocked) {
    _signerError = `On-chain writes are disabled: ${blocked}. No transaction will be sent.`;
    if (BACKEND_PRIVATE_KEY) console.warn(`[chain] ${_signerError}`);
    _signer = null;
    return _signer;
  }

  if (!BACKEND_PRIVATE_KEY) {
    _signer = null;
    return _signer;
  }

  try {
    const key = BACKEND_PRIVATE_KEY.startsWith('0x') ? BACKEND_PRIVATE_KEY : `0x${BACKEND_PRIVATE_KEY}`;
    const wallet = new ethers.Wallet(key, getProvider());

    if (BACKEND_WALLET_ADDRESS && wallet.address.toLowerCase() !== BACKEND_WALLET_ADDRESS.toLowerCase()) {
      _signerError =
        `BACKEND_PRIVATE_KEY derives ${wallet.address} but BACKEND_WALLET_ADDRESS is ${BACKEND_WALLET_ADDRESS}. ` +
        'Registration is disabled until they agree.';
      console.error(`[chain] ${_signerError}`);
      _signer = null;
      return _signer;
    }

    console.log(`[chain] registrar signer loaded: ${wallet.address}`);
    _signer = wallet;
  } catch (err) {
    _signerError = `BACKEND_PRIVATE_KEY is not a valid private key: ${err.message}`;
    console.error(`[chain] ${_signerError}`);
    _signer = null;
  }

  return _signer;
}

/** Why the signer is unavailable, if it is. */
function signerError() {
  return _signerError;
}

/**
 * AlexandriaLibrary connected to the registrar signer, or null if unavailable.
 * Deliberately only the library — no other contract gets a write handle.
 */
function getLibraryWriter() {
  const signer = getSigner();
  if (!signer) return null;
  return new ethers.Contract(resolveAddress('library'), libraryArtifact.abi, signer);
}

// ─── The indexed-string problem ──────────────────────────────────────────────
//
// Every book-scoped event declares `string indexed arweaveHash`. Solidity cannot
// fit a variable-length string into a 32-byte log topic, so it stores
// keccak256(utf8(arweaveHash)) instead and the plaintext is NOT in the log —
// ethers surfaces it as an `Indexed` placeholder, not a string.
//
// keccak256 is one-way, so the listener cannot read the hash off the event. It
// has to go the other direction: hash every arweaveHash it already knows and
// match on the topic. Upload.arweaveHashTopic exists for exactly that lookup.

/**
 * The log topic Solidity emits for a given arweaveHash.
 * @param {string} arweaveHash
 * @returns {string} 0x-prefixed 32-byte keccak256 hash
 */
function topicForHash(arweaveHash) {
  return ethers.id(arweaveHash);
}

/**
 * Pull the raw topic out of a decoded event arg, whichever form ethers used.
 *
 * For `string indexed` params ethers yields an `Indexed` object carrying `.hash`.
 * If a future contract version un-indexes the field we would get a real string
 * instead, and hashing it here keeps the lookup key stable either way.
 *
 * @param {unknown} arg
 * @returns {string|null}
 */
function topicFromEventArg(arg) {
  if (arg == null) return null;
  if (typeof arg === 'string') {
    // Already a 32-byte topic (indexed, pre-decoded) vs. a plaintext hash.
    return ethers.isHexString(arg, 32) ? arg : ethers.id(arg);
  }
  if (typeof arg === 'object' && typeof arg.hash === 'string') return arg.hash;
  return null;
}

module.exports = {
  getProvider,
  getContracts,
  contractAddresses,
  getSigner,
  signerError,
  getLibraryWriter,
  chainWritesBlocked,
  BACKEND_WALLET_ADDRESS,
  topicForHash,
  topicFromEventArg,
  CHAIN_ID,
  POLL_INTERVAL_MS,
  DEPLOYMENT_BLOCK,
  START_BLOCK,
  rpcUrls,
};
